on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    name: test - OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        # https://hexdocs.pm/elixir/1.15.4/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
        include:
          # - otp: "20.3"
          #   elixir: "1.7.4"
          # - otp: "21.3"
          #   elixir: "1.8.2"
          # - otp: "21.3"
          #   elixir: "1.9.4"
          # - otp: "22.3"
          #   elixir: "1.10.4"
          # - otp: "22.3"
          #   elixir: "1.11.4"
          # - otp: "23.3"
          #   elixir: "1.12.3"
          # - otp: "23.3"
          #   elixir: "1.13.4"
          - otp: "24.3"
            elixir: "1.11.4"
          - otp: "24.3"
            elixir: "1.12.3"
          - otp: "24.3"
            elixir: "1.13.4"
          - otp: "24.3"
            elixir: "1.14.5"
          - otp: "25.3"
            elixir: "1.14.5"
          # latest elixir
          - otp: "25.3"
            elixir: "1.15.4"
          - otp: "24.3"
            elixir: "1.15.4"
          - otp: "26.0"
            elixir: "1.15.4"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test --trace
